joint_0:  "hl_yaw"
joint_1:  "hl_hip"
joint_2:  "hl_knee"
joint_3:  "fl_yaw"
joint_4:  "fl_hip"
joint_5:  "fl_knee"
joint_6:  "hr_yaw"
joint_7:  "hr_hip"
joint_8:  "hr_knee"
joint_9:  "fr_yaw"
joint_10: "fr_hip"
joint_11: "fr_knee"

touchdown_0: "fl_td"
touchdown_1: "fr_td"
touchdown_2: "hl_td"
touchdown_3: "hr_td"

imu: "imu"